version: '3'

services:
  arm64:
    build:
      context: .
      dockerfile: Dockerfile.arm64
      args:
        BUILD_FROM: $ARM64_BUILD_FROM
    image: $ARM64_DOCKER_IMAGE_NAME
    container_name: $ARM64_DOCKER_CONTAINER_NAME
    env_file:
      - .env
    ulimits:
      stack: 67108864
      memlock: -1
    ports:
      - "$HOST_SSH_PORT:22"
    volumes:
        - $WORKSPACE_ROOT:$DOCKER_WORKSPACE_ROOT
networks:
  default:
    name: $DOCKER_NETWORK_NAME
    external: true
